### PR TITLE
dict.cc English-German Dictionary Plugin

### PR DESCRIPTION
**Pull request by zzamboni**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s missing `uninstall`. There are [scripts](https://github.com/phinze/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/phinze/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that. Do you need any help?

In addition, why are you adding this here? I see no reason why this couldn’t be added to the main repo (well, or [caskroom/versions](https://github.com/caskroom/homebrew-versions), if more languages can be added).

**Comment by zzamboni** [comment]
Right- I always forget uninstall. I’ll add it ASAP.

I put it in -unofficial because it was published in a blog post, I thought that was part of the criteria? I’d be happy to resubmit it to the main repo is you think it fits there.

**Comment by vitorgalvao** [comment]
> I put it in -unofficial because it was published in a blog post, I thought that was part of the criteria?

Ah, good thinking. However, it is a personal blog, so it isn’t exactly vendorless software — like a personal website, we can trace it back to a particular individual. Compare that to a forum post (which would fall under the criteria you mention) where anyone can create an anonymous account and post anything and vanish after that.

**Comment by zzamboni** [comment]
Good point. I’ll close this PR and resubmit on the main repo, with the addition of  `uninstall`.

**Pull request closed without merging**
