### PR TITLE
Kst plot

### PR DESCRIPTION
**Pull request by f0rdprefect**
included kst-plot as unofficial build. In fact I was asked on the kst mailinglist if I could offer my build, so here I am.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
0. It seems like they offer official releases via sourceforge, why are you submitting yours?
0. Is it a fork, or an unofficial, unmodified build?
0. Please [squash your commits](http://davidwalsh.name/squash-commits-git).
0. Please remove the `freecad_unstable` cask.

**Comment by f0rdprefect** [comment]
1. Yes this is true. But the official build is useless, I tried it, it crashes when I want to import some data. Hence I build from source and it works for me. I have been asked on the mailing list of the kst project if I was willing to contribute my build. Now since I like homebrew this is my attempt tp do so.

2. it is an unmodified build from the git sources the project provides

3. I have not been able to figure out how to correct this. I am only a hobbyist git user. So please can you give me more concrete examples? 

4. Ok I removed freecad_unstable. It was most likely something I overlooked from previous experiments to contribute, but I never finished it. Sorry for that one.

**Comment by vitorgalvao** [comment]
We can worry about the squashing later, as there are more issues with the cask that need to be solved, but can be done at merge time.

However, while I can open their official version (haven’t tried anything besides that), yours immediately crashes on open, on a clean Yosemite VM.

**Comment by alebcay** [comment]
I encountered the same error as @vitorgalvao on my Mountain Lion when demoing this, here's the log for the particular error:
```
Process:         kst2 [8131]
Path:            /Users/USER/Downloads/*/kst2.app/Contents/MacOS/kst2
Identifier:      kst2
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [345]
User ID:         501

Date/Time:       2015-01-03 22:08:01.697 -0500
OS Version:      Mac OS X 10.8.4 (12E55)
Report Version:  10

Interval Since Last Report:          41245431 sec
Crashes Since Last Report:           41281
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      5B86E730-0CC9-371F-5ED4-7793A22F6134

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Users/*/libkst2core.2.dylib
  Referenced from: /Users/USER/Downloads/*/kst2.app/Contents/MacOS/kst2
  Reason: image not found

Binary Images:
       0x1098d1000 -        0x109c79ff7 + (??? - ???) <A2B86407-E9D7-3FE6-9408-BB46D3ADBD73> /Users/USER/Downloads/*/kst2.app/Contents/MacOS/kst2
    0x7fff694d1000 -     0x7fff6950593f  dyld (210.2.3) <6900F2BA-DB48-3B78-B668-58FC0CF6BCB8> /usr/lib/dyld

Model: MacPro3,1, BootROM MultiBeast.tonymacx86.com, 4 processors, Intel Core i5, 3.40 GHz, 8 GB, SMC 1.30f3
Graphics: NVIDIA GeForce GT 640, NVIDIA GeForce GT 640, PCIe, 2048 MB
Memory Module: BANK 3/ChannelB-DIMM1, 8 GB, DDR3, 1600 MHz, Corsair, CMZ8GX3M1A1600C10
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x3112), Atheros 9380: 4.0.72.0-P2P
Network Service: streisand, PPP (L2TP), ppp0
Network Service: Wi-Fi, AirPort, en0
Network Service: Ethernet, Ethernet, en1
Serial ATA Device: Samsung SSD 840 Series, 120.03 GB
Serial ATA Device: WDC WD20EZRX-00D8PB0, 2 TB
Serial ATA Device: ATAPI   iHAS124   W
USB Device: hub_device, 0x8087  (Intel Corporation), 0x0024, 0x1a100000 / 2
USB Device: USB Receiver, 0x046d  (Logitech Inc.), 0xc52b, 0x1a140000 / 5
USB Device: Fitbit Base Station, 0x2687, 0xfb01, 0x1a130000 / 4
USB Device: CLP-310 Series, 0x04e8  (Samsung Electronics Co., Ltd.), 0x328e, 0x1a150000 / 3
USB Device: hub_device, 0x8087  (Intel Corporation), 0x0024, 0x1d100000 / 2
USB Device: A0001, 0x05c6  (Qualcomm, Inc), 0x6765, 0x14200000 / 9
```

**Comment by f0rdprefect** [comment]
Hi, 

ok now I know I have to figure out how to include the libraries needed for kit plot in the cask and to make them findable by the library loader.

I will look into this and get back.

If you have any pointers for me, I would appreciate this.

Thanks,

Matthias

**Comment by vitorgalvao** [comment]
@f0rdprefect The cask itself is mostly fine; any changes should be made to the application itself (since theirs works, it should be possible for yours as well).

**Comment by f0rdprefect** [comment]
Alright, I think I have it. Now I have included all the libraries in the App bundle the App seems to need to run. Since I am still a bit unsure how to proceed from here, I created yet another branch 

https://github.com/f0rdprefect/homebrew-unofficial/tree/kst-plot-new

should I file another pull request? Can these two be merged? Sorry for this silly n00b questions.

Thanks,

Matthias

**Comment by vitorgalvao** [comment]
Not working yet. Tested the new version, and it still crashes on launch.

**Comment by vitorgalvao** [comment]
@f0rdprefect Any progress?

**Comment by f0rdprefect** [comment]
unfortunately no. latest source does no longer build on my MacBook. Will investigate again once another commit is done to the git source repro for kst-plot.

**Comment by vitorgalvao** [comment]
Alright, lets close it in the meantime, then, and reopen (or open a new issue when the time comes). Thank you.

**Pull request closed without merging**
