### PR TITLE
Updated jabber-video to 4.8.8.18390

### PR DESCRIPTION
**Pull request by zerrot**
Changed download url to download from Cisco. However this isn't quite official, as the dmg isn't directly linked from the homepage. Updated license and added vendor tag. Documented the purpose of the postflight stanza, and added zap stanza.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Not that it’s a big deal in this repo and considering the cask itself since we can’t easily confirm it either way, but why change the current `url`?

**Comment by zerrot** [comment]
The Indiana University original url was for 4.8.6. I couldn't find a 4.8.8
dmg on there server. The ciscojabber website should be updated when Jabber
Video is updated, allowing new versions to be more easily maintained in the
cask.

**Comment by zerrot** [comment]
Nevermind, you meant the homepage url. I just changed it because it
redirects there anyway. No particular reason really.

**Comment by vitorgalvao** [comment]
No, I meant the download url, your first reply was correct. However, now that I look closer at it, you just solved the issue with this cask. It can be removed from this repo and added to the main one, because the download host is the same as the homepage (which means we can trust the source, even if under a registration wall).

Would you care to do it?

**Comment by zerrot** [comment]
On a different note, I noticed anytime I create a pull request in the versions or unofficial repos the travis build fails, but in the default repo the builds pass with no issues. Is there something additional I should be doing?

**Comment by vitorgalvao** [comment]
It’s a problem with Travis in those repos that is yet to be solved; nothing being done wrong on your side.

**Comment by zerrot** [comment]
Yeah no problem I can move it. Do you want a new commit, or should I squash
it into one?

**Comment by zerrot** [comment]
Good to know. Thanks.

**Comment by vitorgalvao** [comment]
> Do you want a new commit, or should I squash it into one?

As you prefer.

**Comment by zerrot** [comment]
Just a reminder about this request.

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
